### ISSUE TITLE
[BUG]: Cannot test on phone from project created on PC.

### ISSUE THREAD

**Issue by Dragon-Arrow** [naverz/zepeto-studio-kor#1041]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.6

**What features were you trying to implement?**
Trying to test a project on my mobile device via the generated QR code on the computer.

**What problem did you encounter?**
When making a Zepeto project on my PC, I can't get my mobile device to connect and test it.

After quite a lot of back and forth with another member of your team, we exhausted all the basics such as reinstallation, resetting packages, firewall tests and such.

This is the process of what happens when I create a project and try to test, I've done this about 5 times and get the same results. After creating a new Zepeto default project, a bunch of warnings would show up in the console (I've attached screenshots to showcase these). Sometimes errors would appear as well or instead of. Usually something to do parts of the Zepeto package cache being invalidated or timeout warnings.

The QR code does get generated and it will print out success in the console. However after its scanned the phone will take a while to load, but in the end fails to connect.

This is only happening to me on the PC, I have a laptop of similar spec and everything works fine there.

Copying a previously created PC project to the laptop threw out the "package was invalidated" warning, but otherwise loaded up on the phone perfectly fine.

Creating a working project on the laptop and moving it over to the PC was also tested. It still displayed a warning. But I was actually able to connect on the phone. However this only worked for one test, afterwards subsequent tests did not work.

Additionally installing Git and Git lfs on the laptop caused the project there to display similar warnings, but I was still able to connect on the mobile device just fine. Uninstalling the aforementioned cleared the warnings on the laptop. However replicating this on the PC (which had both installed prior) still resulted in warnings / errors and couldn't connect on the phone still. Might not be of any relevance, but thought I'd note it anyway.

Summary from my email conversation:
- Even after reinstalling, a freshly created PC project still created warnings / errors and I could not connect via the phone.
- Copying over PC projects to laptop had warnings, but still loaded.
- Copying working laptop projects to PC seemed to work only on the first test when you generate the QR code, subsequent attempts didn't work.
- Installing Git and Git lfs made the laptop projects (including brand new ones) experience some of the same oddities as the PC version. But testing still worked.
- Deleting Git and Git lfs from the laptop made those warnings / issues go away on old and new laptop projects. Testing continued to work as usual from there.
- Deleting Git and Git lfs from the computer didn't seem to change much. Though it did break existing projects with a different error.
- The final thing I was asked to do before writing a bug report, was to reset packages to default and try again. Still no luck and was met with the same errors and warnings.

**Please tell us your development environment.**
PC: Windows 10 Pro Edition, Version 21H2, wired router connection
Laptop: Windows 10 Pro Edition
Phone: iPhone 8 software version 15.5 (19F77)

**Please attach the implemented code. If you have a screenshot, please attach it.**

Warnings that show up when creating a new project:
![image](https://user-images.githubusercontent.com/109611011/179832479-3978d9cb-4284-41c3-b210-b743efa3c0d2.png)

Sometimes this error shows up instead when creating a new project. Can also appear after the QR code generates: 
![image](https://user-images.githubusercontent.com/109611011/179817968-85713183-1ce5-4a28-a538-5aac50310ca5.png)

One of the warning messages that can appear on startup
![image](https://user-images.githubusercontent.com/109611011/179818120-72775fd8-225a-4a0e-bfe5-193a36824a2e.png)

More warnings that frequently appear. These also showed up on the laptop once after installing Git.
![after git install(1)](https://user-images.githubusercontent.com/109611011/179818184-3908e86b-c2ac-479b-8ba4-d421e0ec31a8.PNG)

This one has only shown up once after uninstalling Git on the PC.
![image(2)](https://user-images.githubusercontent.com/109611011/179818333-9eee582f-3005-4ee8-be68-ca33edab7280.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 노트북에서는 정상 작동한다면 PC에서의 방화벽 등 네트워크 설정 문제로 추정됩니다.
디스코드에서 비슷한 사례가 있으니 참고 부탁 드립니다.
https://discord.com/channels/1007307468491198485/1025681126821474354
