### ISSUE TITLE
[BUG]: transform.Rotate bug

### ISSUE THREAD

**Issue by Andwhy81kr** [naverz/zepeto-studio-kor#1062]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.5.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
Editor

**What features were you trying to implement?**
Transform Rotate()

**What problem did you encounter?**
Rotate function does not work properly.
Angle is not applied in Route(Axis, Angle) .
this.transform.Rotate(Vector3.up, 0);

**Please tell us your development environment.**
Window 11

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 제보해주신 내용대로 테스트 하였으나 저희 쪽에서 재현되지 않았습니다.
문제가 발생한 상세한 코드를 공유 주시면 도움이 될 것 같습니다.
감사합니다.
