### ISSUE TITLE
안녕하세요 혹시 타입스크립트에서는 순찰하는 AI는 어떻게 구현하나요??

### ISSUE THREAD

**Issue by yj098** [naverz/zepeto-studio-kor#1066]
안녕하세요 혹시 타입스크립트에서는 순찰하는 AI는 어떻게 구현하나요??
유튜브에 c#으로 내비게이션 이용해서 만들 수 있는 강좌는 있는데 타입스크립트 강좌는 없네요 ㅠㅠ
혹시 이것과 관련해서 어떤 강좌를 보면 좋을지 추천 부탁 드립니다 ㅠOㅠ

_Originally posted by @yj098 in https://github.com/naverz/zepeto-studio-kor/discussions/1058_

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 이슈 게시판은 오류 제보를 위한 용도이므로 이슈는 클로징 하겠습니다.
