### ISSUE TITLE
[1.5.1]: Copy of values from Zepeto Script in Inspector generated during Playmode

### ISSUE THREAD

**Issue by Deytooh** [naverz/zepeto-studio-kor#1069]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.5.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
 It's done inside Unity

**What features were you trying to implement?**
 I want to save a prefab

**What problem did you encounter?**
I cant copy values of Zepeto Script's variables show in the Inspector
Int, float등등 is working, but arrays are not working. ( int[], float[] ... )

**Please tell us your development environment.**
Unity

**Please attach the implemented code. If you have a screenshot, please attach it.**

`  public InfoLightmapIndex: int[];
    public InfoLightmapOffsetScale: Vector4[];`

I set the values here during the playmode ( so initially everything arrays are empty )
So after doing some things, arrays are being full
![image](https://user-images.githubusercontent.com/97385930/180904539-36a1da81-87fa-4d0b-a2d0-4e709a99aee1.png)
![image](https://user-images.githubusercontent.com/97385930/180907784-f61c6f03-ce29-485d-a180-6808c9d5c759.png)

But when I try to save this as Prefab, or copy and paste the component, the arrays all become empty.
Like that ->
![image](https://user-images.githubusercontent.com/97385930/180907724-37887eab-281b-43f1-8d37-be34daaaeff4.png)

In debug mode it looks like that ->
![image](https://user-images.githubusercontent.com/97385930/180907784-f61c6f03-ce29-485d-a180-6808c9d5c759.png)

So I guess the problem is that the values from arrays added during runtime are NOT added to the ZepetoScript inside values.

**Comment by jhslee** [comment]
Hello @Deytooh! 👋 

I'm currently having trouble reproducing your issue. If i'm understanding correctly, the issue should occur through the following steps:

1. A script with array values are all set to its initial defaults. 
2. Press play, and modify those values during runtime.
3. Save the prefab to a folder. 
4. Stop play and check that the values do not save and are reverted to their original values. 

These are my variables at each step:

Initial Defaults:
<img width="343" alt="Screen Shot 2022-08-03 at 2 51 14 PM" src="https://user-images.githubusercontent.com/105688184/182719479-3f66690f-791e-4e1e-912e-047e873ba422.png">

Runtime Modifications:
<img width="353" alt="Screen Shot 2022-08-03 at 2 52 00 PM" src="https://user-images.githubusercontent.com/105688184/182719511-39cb8ace-d7e8-4d4a-8e5f-7f7a54bd87e5.png">


Save to prefab, and checked values after stopping play:
<img width="351" alt="Screen Shot 2022-08-03 at 2 52 13 PM" src="https://user-images.githubusercontent.com/105688184/182719637-7addf0cb-08d9-4b6e-b589-6f74d257512c.png">
<img width="348" alt="Screen Shot 2022-08-03 at 2 52 26 PM" src="https://user-images.githubusercontent.com/105688184/182719662-108d5d36-e38d-490f-97f8-8b1c259eb2fa.png">


If theres any steps im missing to reproduce the issue, please let me know!

**Comment by Deytooh** [comment]
Hi ~~ !

Oh thank you very much !!

"2.Press play, and modify those values during runtime."
For this second step, you need to modify the values during runtime but through script ! through the inspector it works, but if the values are modified through the script, it doesnt get updated

**Comment by Deytooh** [comment]
@jhslee Hey ~ Any update about this issue ? It is quite a problem 😢

**Comment by Zepeto-TechEvangelist** [comment]
Hello, it will be applied in the next version. thank you
