### ISSUE TITLE
[BUG]: 일부 아바타의 눈알이 피부 모델링을 뚫고 렌더링이 됩니다.

### ISSUE THREAD

**Issue by YSHFM** [naverz/zepeto-studio-kor#1122]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
- 1.5.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
- 3.14.2

**What features were you trying to implement?**
- 

**What problem did you encounter?**
- 인 월드 내에서 캐릭터의 렌더링에 차이가 있습니다.

**Please tell us your development environment.**
-  iPadOS 15.5

**Please attach the implemented code. If you have a screenshot, please attach it.**
![iOS 이미지 (1)](https://user-images.githubusercontent.com/106574541/182749437-2f9efda0-b6de-4f79-8cb6-60147405f882.jpg)
![iOS 이미지](https://user-images.githubusercontent.com/106574541/182749440-dded393d-67a3-4229-b903-26e97413f956.jpg)
해당 아바타의 끝 눈매에서 눈알메시가 피부 메시를 뚫고 렌더링되는 것을 확인하였습니다.
플레이어 마테리얼의 변경사항은 없습니다.

하단은 해당 캐릭터의 커스터마이징입니다.

![iOS 이미지 (3)](https://user-images.githubusercontent.com/106574541/182750672-14108bb6-2837-4cc4-84f5-2a2128819a36.jpg)
![iOS 이미지 (2)](https://user-images.githubusercontent.com/106574541/182750676-1634d330-b405-490d-be96-b35a457fc45b.jpg)

**Comment by Cha-SeongHun** [comment]
아이폰 기종에서는 재현되지 않으며 안드로이드 환경에서 동일증상 재현되네요
제 환경에서는 아래 증상들이 확인됩니다

- 흰눈동자가 눈꼽 부분으로 튀어나오는 현상
- 귀 밑 턱 폴리곤이 깨지는 현상

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 제페토 캐릭터는 4 Bones를 기준으로 리깅되어 있기 때문에 2 Bones에서는 제보해주신 것처럼 얼굴 부위 위주로 버텍스 일부가 깨지게 됩니다. 
Quality Settings에서 해당 옵션을 4 Bones로 적용하면 더 이상 발생하지 않고, 캐릭터 얼굴이 정상적으로 노출됩니다.
![108141472-a0bc1800-7078-11eb-83b3-005a58211d04](https://user-images.githubusercontent.com/100118650/182817059-ff58b807-f90b-4937-b6d5-4f79ba7ad5ed.png)
 
추후 업데이트에서는 Quality Settings 시 4 Bones로 고정되도록 변경할 예정입니다.

감사합니다.

**Comment by zlmrzlo** [comment]
안드로이드 환경에서 4 Bones로 고정하면
아이폰에서는 월드가 돌아가는데 
안드로이드폰에서는 제페토앱 자체가 강제 종료되는 문제가 발생할 가능성이 높습니다.

안드로이드폰이 아이폰보다 성능면에 뒤쳐지는 것이 현실입니다.
