### ISSUE TITLE
[BUG]: PostProcessProfile.GetSetting not working on Android

### ISSUE THREAD

**Issue by eaglecat** [naverz/zepeto-studio-kor#1125]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.5.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.14.2

**What features were you trying to implement?**
To change properties of post process component.

**What problem did you encounter?**
TryGetSettings and GetSetting **_both work on Unity editor(Windows),  throw error on android._**
`PostProcessVolume.profile.GetSetting is not a function`
![image](https://user-images.githubusercontent.com/18285820/182804576-7a64d15e-1263-40a5-83fe-bef5463ada1b.png)
I also tried 'Reimport all' all assets

**Please tell us your development environment.**
Window 11, Android 11

**Please attach the implemented code. If you have a screenshot, please attach it.**
```
this.postProcessVolume = this.GetComponent<PostProcessVolume>();
this.bloom = this.postProcessVolume.profile.GetSetting<Bloom>();
```
```
this.postProcessVolume = this.GetComponent<PostProcessVolume>();
let bloomRef = $ref<Bloom>();
const result2 = this.postProcessVolume.profile.TryGetSettings<Bloom>(bloomRef);
this.bloom = bloomRef.value;
var b = $unref<Bloom>(bloomRef);
```

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 해당 이슈 다음 버전에서 해결될 예정입니다. 감사합니다.
