### ISSUE TITLE
[BUG]: Cannot touch outside of screen on iPhone in `1.5.1`

### ISSUE THREAD

**Issue by hyunjoon-park-metaspace** [naverz/zepeto-studio-kor#1153]
## Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)
1.5.1

## Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)
3.14.2

## What features were you trying to implement?
I want to fix the issue that users cannot touch outside of screen on iPhone in previous ZEPETO versions.

## What problem did you encounter?
It seems not fixed in `1.5.1`.

## Please tell us your development environment.
iPhone 13 Pro Max, iOS 15.5

**Comment by zlmrzlo** [comment]
궁금한 게 이전 버전에서는 터치가 잘 되었나요?
아이폰은 SafeArea를 고려해서 코딩을 해야 합니다.
이러한 부분을 한 번 검색해보시는 것이 좋을 듯 합니다.

**Comment by hyunjoon-park-metaspace** [comment]
@zlmrzlo `1.5.0`을 말씀하시는거라면 그 버전에서는 테스트해보지 않았습니다.

UI 배치는 SafeArea 고려가 되어있습니다만, SafeArea 밖에 있는 element의 터치 이벤트가 대부분 무시되는게 문제입니다.

`1.5.0`에서 해결되었다고 공지되어있지만 `1.5.1`에서 테스트시 여전히 같은 문제가 있어 리포트한 것입니다.

**Comment by zlmrzlo** [comment]
@hyunjoon-park-metaspace Canvas의 범위가 SafeArea 밖으로 넘어가서 터치 이벤트가 대부분 무시된다는 의미라면 터치 이벤트가 필요한 부분을 SafeArea에 넣으시면 될 것 같네요. 만약 이 질문이 답이 안된다면 굳이 SafeArea 밖에 element를 넣으려고 하는 이유가 있나요?

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 제보주신 스크린 외부 터치 불가 이슈에 대해 저희가 여러 디바이스에서 테스트해 보았으나 이상 없음으로 판단됩니다.
관련해서 계속해서 어려움을 겪으신다면 보다 상세한 수정 방향 및 오류 상황 보고를 부탁 드립니다.
감사합니다.

**Comment by Cha-SeongHun** [comment]
월드패키지 1.7.0버전 시스템에서 아직 재현되는 것을 확인하였습니다.
테스트에 사용한 모바일 기기는 iPhone 14 Pro Max 입니다

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 최신 월드에서도 발생하는지 확인 부탁드리며 발생시 디스코드를 통해 제보 부탁 드립니다.
감사합니다.
