### ISSUE TITLE
[BUG]: Characters do not spawn in mobile environments.

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#1154]
## Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)
`1.5.1`

## Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)
`3.14.2`

## What features were you trying to implement?
An attempt was made to spawn a character when an external multiplayer connected.

## What problem did you encounter?
Multiplayer characters are not created.

## Please tell us your development environment.
`Window 11` `Android 12`

## Please attach the implemented code. If you have a screenshot, please attach it.
The log that occurs when character creation is completed normally is as follows. (Local player character creation)
![Screenshot_5](https://user-images.githubusercontent.com/100827088/183889855-9e5adbd5-c5c2-4968-904c-c443a33f6705.png)

However, if you create a multiplayer character, a C# Exception is thrown as shown below, and it is not created.
![Screenshot_6](https://user-images.githubusercontent.com/100827088/183889964-f32e2aaa-07e6-4f82-a490-cc951aa6c3f3.png)

The code used to create the character is below.
```ts
ZepetoPlayers.instance.CreatePlayerWithUserId(userId, new SpawnInfo(), false);
```

---

The test environment is as follows.
- Windows desktop (Server, Client 1)
- Android (Client 2)
- Android (Client 3)

At this time, only in Client 1, the characters of Client 2 and Client 3 are created and displayed.
In Client 2, Client 3, an error occurs while creating another character.

The clients all use the same logic, but only on mobile I get an error during character creation.
Also, the tests were working fine until a day before I posted this issue with the same code (at least 2 months).
It started happening all of a sudden with no project scene and code modifications.

**Comment by IndiaInk10** [comment]
https://github.com/naverz/zepeto-studio-kor/discussions/1170#discussioncomment-3389772
혹시 저랑 같은 현상일까 해서 공유해봅니다!

**Comment by ttoowa** [comment]
> https://github.com/naverz/zepeto-studio-kor/discussions/1170#discussioncomment-3389772
> 혹시 저랑 같은 현상일까 해서 공유해봅니다!

답변 감사합니다!
 코드상에서 캐릭터 스폰 이벤트조차 발생하지 않아 캐릭터를 아예 제어할 수 없는 상황이라 다른 케이스 같습니다

**Comment by Cha-SeongHun** [comment]
답변 감사합니다!
코드상에서 캐릭터 스폰 이벤트조차 발생하지 않아 캐릭터를 아예 제어할 수 없는 상황이라 다른 케이스 같습니다

---

Start로직에서 로컬플레이어 캐릭터 생성 후 멀티플레이어 캐릭터 생성 시
로컬플레이어는 정상스폰, 멀티플레이어는 생성 중 Exception이 발생하는 것을 추가로 확인하였습니다.
(동일하게 모바일에서만 발생)

**Comment by Cha-SeongHun** [comment]
재현방법을 찾게 되어 공유합니다.. 코루틴 쪽 이슈로 보이며 해결이 필요해 보입니다.


```ts
// 오류 발생 케이스
private SpawnPlayer() {
  this.StartCoroutine(this.SpawnPlayerRoutine());
}
private *SpawnPlayerRoutine() {
  ZepetoPlayers.instance.CreatePlayerWithUserId("{USER_ID}", new SpawnInfo(), false);
}
```

```ts
// 오류가 발생하지 않는 케이스
private SpawnPlayer() {
  this.StartCoroutine(this.SpawnPlayerRoutine());
}
private *SpawnPlayerRoutine() {
  ZepetoPlayers.instance.CreatePlayerWithUserId("{USER_ID}", new SpawnInfo(), false);
  return;
}
```

코루틴을 자동종료되도록 구현하면 '모바일'환경에서 오류가 나면서 로직이 동작하지 않게 됩니다.
코루틴을 내부에서 명시적으로 종료시켜주면 정상적으로 동작합니다.

**Comment by Cha-SeongHun** [comment]
정정합니다. 코루틴 이외 Start 및 Update 함수에서 캐릭터 스폰시에도 재현됩니다.

Exception 발생 위치인 ZEPETO.GameSystem.GameSystemService.OnZepetoPlayersAwake 함수 코드를 볼 수 있으면 원인을 금방 알 수 있을 것 같은데 볼 수 없는 코드의 이슈 트래킹을 혼자 하고 있으니 모래사장에 바늘 찾는 느낌입니다.

공식적인 피드백을 기대하긴 어려울까요??

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 내부에서 해당 내용 검토 및 확인해 보겠습니다.

**Comment by Zepeto-TechEvangelist** [comment]
OnZepetoPlayersAwake의 경우 ZepetoCharacter 패키지내에 포함된 이벤트 핸들러입니다.
해당 OnZepetoPlayersAwake 타이밍에는, 캐릭터 컨트롤러와 관련된 다음 이벤트 핸들러를 바인딩합니다.
```typescript
ZepetoPlayers.instance.OnAddedPlayer
ZepetoPlayers.instance.OnRemovedPlayer
```

크리에이터가 컨텐츠레벨에서 임의의 핸들러를 달아놨을 때, 컨텐츠 로직부분에 Exception 발생할 경우
Main-Unity에서 도는 부분이 돌지 않는 케이스가 발생할 가능성이 확인 되었습니다.

이에 따라, 다음 마일스톤때 본체 내에서 사용되는 핸들러와
크리에이터가 바인딩하는 핸들러를 분리하는 작업을 추가할 예정입니다.

갑자기 에러가 발생하는 부분에 대해서는 좀더 상황을 알려주시면 문제 파악에 도움이 될 것 같습니다.
1. 컨텐츠 로직에 수정이 있는지
2. 사용하는 패키지 버전에 변경이 있는지
3. 앱버전에 변경이 있는지

확인 부탁 드립니다.
