### ISSUE TITLE
월드맵 업로드시 확장자 궁금합니다.패키지 폴더로 업로드 하는건가요? 월드맵왕초보라 ..그리고 유니티에서 작업한 맵 테스트 오류가  나면 월드맵 심사제출에도 문제가 생기는거죠? 아시는분 답변 부탁드립니다.

### ISSUE THREAD

**Issue by daffodil49** [naverz/zepeto-studio-kor#1172]
월드맵 업로드시 확장자 궁금합니다.패키지 폴더로 업로드 하는건가요? 월드맵왕초보라 ..그리고 유니티에서 작업한 맵 테스트 오류가  나면 월드맵 심사제출에도 문제가 생기는거죠? 아시는분 답변 부탁드립니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 월드맵 업로드시 작업 폴더 내의 build 폴더 > .zepetopackage 확장자의 패키지 파일을 업로드하시면 됩니다.
맵 테스트 오류가 나면 심사시 리젝이 되어서 새로운 버전으로 심사 요청을 주셔야 합니다.

추후에는 이슈 게시판 목적과 양식에 맞춰 올려주시기를 부탁 드립니다. 🙏
감사합니다.
