### ISSUE TITLE
[BUG]: Freezing the world when recording the smartphone screen after launching the world

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#1203]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.6.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
ex) 3.15.1

**What features were you trying to implement?**
Screen recording via smartphone screen recording function under normal circumstances

**What problem did you encounter?**
As soon as the screen recording starts, the world freezes.

**Please tell us your development environment.**
Android12 / Galaxy S21 Ultra 
Test progress after registering as a temporary state

The world freezes when you start recording the screen.
I used the screen recording function in the Galaxy.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요 제보 감사합니다. 이 이슈는 외부 요인에 의한 부분이어서 저희 쪽에서 해결이 불가한 점 양해 부탁 드립니다.
