### ISSUE TITLE
[BUG]: If you send after entering chat in the world, the world freezes

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#1204]
Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)
ex) 1.6.0 / 1.5.1 / 1.5.0

Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)
ex) 3.15.1

What features were you trying to implement?
World Freezing when entering World Chat under normal circumstances

What problem did you encounter?
World Freezing as soon as chat input is completed

Please tell us your development environment.
Android12 / Galaxy S21 Ultra
Test progress after registering as a temporary state

When you enter chat in the world, the world is frozen in a specific terminal.
If you send after entering chat, it stops and nothing happens after that.

ZEPETO.World works normally in version 1.4.1.

**Comment by Zepeto-TechEvangelist** [comment]
해당 이슈 월드 버전 1.4.1에서 수정되었습니다.
