### ISSUE TITLE
[BUG]: After registering as a temporary state, you are not invited to the world when testing.

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#1205]
Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)
ex) 1.6.0

Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)
ex) 3.15.1

What features were you trying to implement?

What problem did you encounter?

Please tell us your development environment.
Android12 / Galaxy S21 Ultra
Test progress after registering as a temporary state

Intermittently, when I send an invitation to an iOS -> Android or iOS -> iOS user, nothing happens.
It looks like you are not invited.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 해당 현상이 최근에도 나타나고 있는지 확인 요청 드립니다.

**Comment by crash-k** [comment]
I'll close it because there's been no response for a long time.
