### ISSUE TITLE
[BUG]: Exception when assigning null to sprite of Image component

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#1234]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.6.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.15.1

**What features were you trying to implement?**
I tried to place an Image in Unity UGUI Canvas and set null to Image.sprite with ZEPETO Script.
In general, making a sprite null is used a lot, so I tried working with the same process, but I get an exception.

**What problem did you encounter?**
Exception when assigning null to Image.sprite via ZEPETO Script.

**Please tell us your development environment.**
Windows 11

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 어떤 예외가 발생하는지 어떤 결과를 의도했는지 등을 양식에 맞춰서 상세히 제보해 주시면 감사 드리겠습니다 :)

**Comment by Cha-SeongHun** [comment]
안녕하세요, 몇가지 내용 보충하여 업데이트해두었습니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요. 이슈 해결을 위해 저희쪽에서 재현을 시도했으나 재현이 되지 않고 있습니다.
혹시 최신 월드에도 해당 현상이 발생하고 있는지요?
