### ISSUE TITLE
[BUG]: Chat bubbles are not displayed intermittently on iOS

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#1239]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.15.0

**Please tell us your development environment.**
iOS 15.5

The speech bubble above the character's head is not intermittently exposed when entering chat

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 채팅 내용에 상관없이 간헐적으로 노출되지 않는 상황일까요?

**Comment by xowjd913** [comment]
> 

네 채팅 내용과는 상관없이 간헐적으로 노출되지않습니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 저희 쪽에서 재현되지 않는 이슈입니다.
최신 월드에서도 발생하는지 확인 부탁드리며 발생시 디스코드를 통해 제보 부탁 드립니다.
감사합니다.
