### ISSUE TITLE
[BUG]: OnMouseDown does not work in world 1.6.0.

### ISSUE THREAD

**Issue by ryusiin** [naverz/zepeto-studio-kor#1269]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.6.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
ex) 3.13.6

**What features were you trying to implement?**
The previously used OnMouseDown does not work.

**What problem did you encounter?**
The existing OnMouseDown didn't work, so I started a new project and ran it after updating the world to 1.6.0, so it didn't work.
Running through the 1.5.1 world, OnMouseDown works without any issues.

**Please tell us your development environment.**
Window 10

**Please attach the implemented code. If you have a screenshot, please attach it.**
![image](https://user-images.githubusercontent.com/5895396/188820134-62d53abf-2703-4744-b90f-4f983095b09f.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요. 이슈 해결을 위해 저희쪽에서 재현을 시도했으나 재현이 되지 않고 있습니다.
혹시 최신 월드에도 해당 현상이 발생하고 있는지요?

**Comment by ryusiin** [comment]
답변이 늦었습니다.

1.7.0에서 문제 없이 진행됩니다:)
