### ISSUE TITLE
[1.7.0] Compare Tag doesnt work

### ISSUE THREAD

**Issue by Deytooh** [naverz/zepeto-studio-kor#1291]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.7.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
ex) 3.16.200

**What features were you trying to implement?**
Ex) detect a type of object with a tag

**What problem did you encounter?**
CompareTag method is not functional 
it works on unity but when I build it doesnt work

**Please tell us your development environment.**
Windows 10

**Please attach the implemented code. If you have a screenshot, please attach it.**

`E/Unity: Tag: TurnableUI is not defined.
    ZEPETO.Script.InstanceFunc`3:Invoke(TSelf&, T0)
    ZEPETO.Script.WrapperContextExtensions:Wrap(WrapperContext, InstanceFunc`3, TSelf&, Boolean, WrapperType)
    ZEPETO.Script.WrapperContextExtensions:Wrap(WrapperContext, InstanceFunc`3, Boolean, WrapperType)
    UnityEngine.CoreModule.Generated.UnityEngine_Component_Wrap:M_CompareTag(IntPtr, IntPtr, IntPtr, Int32, Int64)`

but if I print the gameObject.tag it tells me the correct tag, just the method CompareTag doesnt work

**Comment by crash-k** [comment]
It's working normally now.
