### ISSUE TITLE
아이템 먹는 월드

### ISSUE THREAD

**Issue by ftbin** [naverz/zepeto-studio-kor#1292]
공식 예제를 다운 받았는데 getitem이 있는 씬은 없더라구요ㅠㅠ 혹시 어떻게 적용해야할까요?

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요. 이곳은 버그를 제보하는 이슈게시판입니다. 이슈는 close하도록 하겠습니다.
앞으로는 디스코드를 이용해 주세요 😄

문의주신 내용에 답변 드리지만 Chapter 별로 폴더가 정리되어 있습니다.
Chapter2 항목을 살펴보세요.
감사합니다.
