### ISSUE TITLE
[BUG]: Array variable disappearing intermittently in inspector

### ISSUE THREAD

**Issue by Zepeto-TechEvangelist** [naverz/zepeto-studio-kor#1293]
### Issue reported by Discord

**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.6.0

**What problem did you encounter?**
when I check some variables through the Inspector window, there is a situation where it cannot be displayed with the phrase that there is an editor error. The problem is that if you proceed with the actual play or build, it looks well applied, but when you stop playing and look at it on the editor screen, it seems to be missing. And it's mostly fine, but sometimes when I build it, it doesn't actually work and you get an error. Currently, it occurs in only one script and an error occurs in the Texture array variable. The world package version is 1.6.0.

**Please attach the implemented code. If you have a screenshot, please attach it.**
![unknown](https://user-images.githubusercontent.com/100118650/194516799-6d7966c2-82a7-41bb-abf4-7dafb322a606.png)

**Comment by adamwawrzynkowski** [comment]
I have the same issue. This bug is present also on compilation error, and after you fix the error - whole Zepeto Script Component is cleared

**Comment by Zepeto-TechEvangelist** [comment]
Hello, this is an issue resolved in World 1.8.0.
I will close the issue.
