### ISSUE TITLE
[BUG]: ERROR, code =>-1, message => connection not found

### ISSUE THREAD

**Issue by ParkGoeun00** [naverz/zepeto-studio-kor#1294]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.7.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.16.100

**What features were you trying to implement?**
I want to play zepeto project in multiplay.

**What problem did you encounter?**
zepeto character is not created when i clicked unity play button. and onJoin function in index.ts is not called. 

**Please tell us your development environment.**
Window11

**Please attach the implemented code. If you have a screenshot, please attach it.**
![image](https://user-images.githubusercontent.com/88637856/195800011-044d1546-8485-4711-b8db-5dcb2e3bd34f.png)
![image](https://user-images.githubusercontent.com/88637856/195800181-ff7a51e9-29bc-4e39-8482-d7cfa9b9d3eb.png)
![image](https://user-images.githubusercontent.com/88637856/195800387-6f4f9ac4-4bb2-4573-8622-475ecd09849a.png)
![image](https://user-images.githubusercontent.com/88637856/195800504-3c028506-5525-4fd0-a807-945ea06773a7.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 저희 쪽에서 재현되지 않는 이슈입니다.
최신 월드에서도 발생하는지 확인 부탁드리며 발생시 디스코드를 통해 제보 부탁 드립니다.
감사합니다.
