### ISSUE TITLE
[BUG]: Can't add Zepeto Scriptable Objects to a public Zepeto Scriptable Objects array in the inspector.

### ISSUE THREAD

**Issue by hoshpup** [naverz/zepeto-studio-kor#1295]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.6.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.16.100

**What features were you trying to implement?**
Trying to add Zepeto Scriptable Objects to a public array in the inspector.

**What problem did you encounter?**
Inspector errors and does not allow you to drag and drop the Zepeto Scriptable Objects into the array fields. No errors in the console, but does display a small error message near the array (shown in the screenshot)

![error zepeto 1](https://user-images.githubusercontent.com/22479235/195877484-459ac95f-416c-4618-83f1-93ffb445a4ed.png)

**Please tell us your development environment.**
Windows 10

**Comment by Zepeto-TechEvangelist** [comment]
해당 이슈 1.8.0에서 수정 완료되어 이슈 클로즈하겠습니다. 감사합니다.
