### ISSUE TITLE
[BUG]: Unity gets stuck when attempting to close the project

### ISSUE THREAD

**Issue by JesseAtRelish** [naverz/zepeto-studio-kor#1296]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.4.0

1.6.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
ex) 3.13.6

3.16.100

**What features were you trying to implement?**
Ex) I want to interact with a specific object when I get close to it.

Developing in Unity IDE 2020.3.9f1

**What problem did you encounter?**

Attempts to close the IDE fail. Unity pops up a 'Hold on' / 'Application.Quit' progress bar that never completes. We must force quit the application. 

This doesn't seem to happen if we open the project and immediately close. 
This doesn't seem to happen if we only start the multiplayer server.
This doesn't seem to happen if we only compile typescripts
This doesn't seem to happen if we only login to our zepeto account

Seems to happen after multiple play sessions.

**Please tell us your development environment.**
WIndows 11

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 저희 쪽에서 재현되지 않는 이슈입니다.
최신 월드에서도 발생하는지 확인 부탁드리며 발생시 디스코드를 통해 제보 부탁 드립니다.
감사합니다.
