### ISSUE TITLE
서버에서 setInterval 함수를 사용할수 없습니다

### ISSUE THREAD

**Issue by smilejsu82** [naverz/zepeto-studio-kor#710]
**Label 설정 필수
라벨 설정하는 부분을 못찾겠어요 

**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.2.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
제페토 버전과 무관 

**어떤 기능을 구현하려고 했나요?
서버에서 setInterval 함수를 사용하려고 합니다 

**어떤 문제가 발생 하였나요?
에러가 납니다 

**개발 환경을 알려주세요.
Window 11

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.
![image](https://user-images.githubusercontent.com/50188795/167158133-5725298d-1d3f-48a1-bcd1-63271f52a1a4.png)
![image](https://user-images.githubusercontent.com/50188795/167158167-96c5ced3-f46b-4df5-b0cc-d7a4c031359f.png)

기타 
setTimeout은 잘 동작 합니다

**Comment by Zepeto-TechEvangelist** [comment]
setTimeout, setInterval, process.nextTick, setImmediate 는 현 적용 불가능 합니다.
에디터 상에서는 일부 열려있으나, 운영서버에서는 막혀있습니다. (코드 동작 안함)
해당 부분은 내부에서 일부 재구현하여 오픈 예정 입니다.
지금은 onTick 함수를 통해 구현해야 합니다.
