### ISSUE TITLE
프로젝트가 컴파일되지 않습니다

### ISSUE THREAD

**Issue by hyunjoon-park-metaspace** [naverz/zepeto-studio-kor#723]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.3.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
앱 버전이랑 관련이 없습니다

**어떤 기능을 구현하려고 했나요?
프로젝트를 빌드하려고 했습니다

**어떤 문제가 발생 하였나요?
프로젝트를 열면 아래와 같은 에러가 납니다.

```
System.NullReferenceException: Object reference not set to an instance of an object
  at ZEPETO.Script.Editor.TypescriptIDEInitializer.EnsureVSCodeLanuch () [0x000af] in <868383e0843440a29867f5de362dd887>:0 
  at ZEPETO.Script.Editor.TypescriptIDEInitializer.Initialize () [0x00021] in <868383e0843440a29867f5de362dd887>:0 
  at ZEPETO.Script.Editor.ZepetoScriptEnvironments.InitializeEnvironments () [0x00062] in <868383e0843440a29867f5de362dd887>:0 
UnityEngine.Debug:LogError (object)
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeEnvironments ()
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeTypescript ()
```

이후 상단 메뉴에서 `ZEPETO` > `Script` > `Rebuild All`을 누르면 아래와 같은 에러가 납니다.

```
Module '"ZEPETO.Multiplay"' has no exported member 'Sandbox'. (at Assets/Scripts/World.multiplay/Lobby.ts:1))
Module '"ZEPETO.Multiplay"' has no exported member 'SandboxPlayer'. (at Assets/Scripts/World.multiplay/Lobby.ts:1))
```

서버를 실행할 수 없어서 테스트가 불가능합니다.

**개발 환경을 알려주세요.
M1 MacBook Pro MacOS 12.3

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

<img width="824" alt="스크린샷 2022-05-10 오후 1 57 20" src="https://user-images.githubusercontent.com/100826500/167545512-7968fcb3-c941-4694-b23a-3ba81e200d20.png">

**Comment by hyunjoon-park-metaspace** [comment]
더 확인해본 결과 `package.json` 파일에 아래 항목이 있는데요.

```
"@zepeto/sandbox": "file:Library/Packages/zepeto-sandbox.tgz"
```

하지만 해당 파일은 존재하지 않는 상태입니다. 이 문제로 인해 지금 프로젝트 진행이 아예 불가능합니다.

어떤 방법을 시도해도 복구가 안 됩니다.

**Comment by hyunjoon-park-metaspace** [comment]
새 프로젝트를 판 뒤에 에셋을 옮겨도 안 됩니다

**Comment by Zepeto-TechEvangelist** [comment]
이슈 확인 중입니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 내부에서 이슈 재현이 되지 않아 가능하시다면 아래 이 메일로 프로젝트 파일 전달 부탁드립니다.
[yura.hwang@naverz-corp.com](mailto:yura.hwang@naverz-corp.com)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 전달 드린 이메일 내용대로 해결이 되셨는지 궁금합니다.

더불어 컴파일 오류를 해결하는 ZEPETO.Script 1.3.4 프리뷰 패키지를 업데이트 하였습니다. 
아래의 방법으로 적용 가능합니다. 

Window → Package Manager 버튼을 눌러서 Package Manager를 오픈 → [ZEPETO.Script]를 누르고 오른쪽 하단의 Update 버튼을 누릅니다.
1.3.4 preview 버전 업 후 컴파일러 재실행을 위해 유니티를 재시작 해 주세요.

<img width="797" alt="174784909-cdeea83d-0881-4f56-a6cf-7a58a9a4415c" src="https://user-images.githubusercontent.com/100118650/176088462-5bbd8158-bc79-46fb-8fe1-dd702495c103.png">

감사합니다.

**Comment by hyunjoon-park-metaspace** [comment]
안녕하세요, 답장이 늦어 죄송합니다.

말씀해주신대로 패키지를 업데이트하니 프로젝트가 다시 문제 없이 컴파일됩니다.

감사합니다!
