### ISSUE TITLE
[BUG] : Character physics simulation does not update properly.

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#724]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.3.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.12.1`

**What features were you trying to implement?**
```
-
```

**What problem did you encounter?**
```
When spawning a character, physics simulations such as **hair** and **accessories** do not work properly.
```

**Please tell us your development environment.**
`Window 11` `Android 12 (갤럭시 폴드2)`

**Please attach the implemented code. If you have a screenshot, please attach it.**

![Honeycam 2022-05-10 14-16-51](https://user-images.githubusercontent.com/100827088/167547454-9a7e6105-4eae-455f-a579-24dc14bb4f33.gif)
```
Please refer to the doll on the back
```

![Hair](https://user-images.githubusercontent.com/100827088/169780817-00171815-8f0c-4077-96ce-be17bfb90c1a.gif)

**Comment by Zepeto-TechEvangelist** [comment]
엔진쪽에서 확인 중에 있습니다.
