### ISSUE TITLE
[BUG] : Unintentional packet reception log

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#726]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.3.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.12.1`

**What features were you trying to implement?**
```
-
```

**What problem did you encounter?**
```
When a packet sent from the server is received, a log with '[GS]' prefix is ​​generated.
An issue was created because it was difficult to check other logs because unintended logs were continuously generated in large numbers.
```

**Please tell us your development environment.**
`Windows 11` `Android 12 (Galaxy Fold 2)`

**Please attach the implemented code. If you have a screenshot, please attach it.**
![image](https://user-images.githubusercontent.com/100827088/167558488-5a54dcdf-67d5-40c9-9a31-66838041bdf3.png)

**Comment by Zepeto-TechEvangelist** [comment]
수정 완료되었고 업데이트 시기는 논의 중에 있습니다.
