### ISSUE TITLE
PC 에디터상에서 horizontal orientation으로 설정해도 세로 VPad가 표시됩니다

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#741]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)**
`1.3.0`

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)**
`3.12.1`

**어떤 기능을 구현하려고 했나요?**
```
-
```

**어떤 문제가 발생 하였나요?**
```
PC 유니티 에디터에서 Horizontal orientation으로 설정 후 플레이 시
세로 화면 기준으로 VPad가 표시됩니다. (Vertical Controller를 사용하게 되어 화면 전체를 버튼이 덮게 됩니다)

모바일에서는 정상적으로 출력되지만
설정에 따라 에디터에서도 가로 화면 기준 VPad가 나타난다면 테스트가 더 용이할 것 같습니다.
```

**개발 환경을 알려주세요.**
`Window 11` `Android 12`

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.**
![image](https://user-images.githubusercontent.com/100827088/168028551-49c96173-fc97-4599-9bb7-805978521110.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 세로로 보여지는 것은 유니티 Game 뷰의 해상도 설정으로 변경하실 수 있습니다.
세로모드로 설정하면 디바이스에서는 세로로 보여지지만 유니티 에디터 상으로는 게임뷰의 해상도를 따르기 때문에 그렇습니다.

세로모드 설정한 후 아래와 같이 직접 세로 해상도를 추가해 주세요.
![스크린샷 2022-06-08 오전 11 19 38](https://user-images.githubusercontent.com/100118650/172517341-5bf21ce0-7227-488c-a613-e9a6378775b0.png)

세로 해상도 예시
![스크린샷 2022-06-08 오전 11 19 14](https://user-images.githubusercontent.com/100118650/172517291-b00545ab-f836-4392-95c8-1d86b64fa2f3.png)

감사합니다.

**Comment by Cha-SeongHun** [comment]
세로모드는 정상적으로 나타나나 가로모드 시 문제가 되고 있는 상황입니다. 질문을 다시 확인해주시면 감사하겠습니다

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 말씀하신대로 유니티 에디터 설정 상으로는 V-pad가 Vertical Prefab으로 보여지도록 되어 있습니다.
에디터 테스트를 위해 이 부분을 개선하는 작업이 필요하며 서버 안정화 등의 작업이 우선시 되다보니
이 이슈는 추후 개선하는 것으로 처리될 예정입니다.
양해 부탁 드립니다.

만약 에디터 테스트를 위해서라면 아래와 같이 설정하면 된다는 방법이 있습니다. 😅
![스크린샷 2022-06-08 오후 6 30 14](https://user-images.githubusercontent.com/100118650/172583312-b4c155bc-4805-4a8c-a561-b2783b05c529.png)

감사합니다.

**Comment by Zepeto-TechEvangelist** [comment]
월드 1.8.0에서 해결되었습니다. 감사합니다.
