### ISSUE TITLE
모바일에서 ProjectSetting/Quality 가 적용되지 않음

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#751]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)**
`1.3.0`

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)**
`3.12.1`

**어떤 기능을 구현하려고 했나요?**
```
Quality 세팅을 통해 모바일에서 보여지는 라이트 세팅을 조절하려고 했습니다.
```

**어떤 문제가 발생 하였나요?**
```
모바일에서 월드 접속 시 Quality 세팅값들이 모두 바뀌어버립니다.

개발중인 월드에서 QR코드를 통해 접속해도 마찬가지이며,
이미 서비스 중인 월드에도 갑자기 증상이 발생했습니다.
서비스중인 월드의 경우 월드를 재업로드하지 않았고 예전에는 증상이 없었음에도 언제부터인지 갑자기 발생했습니다.

예전에는 퍼블리시 이후에도 의도한 대로 렌더링이 잘 되었기 때문에 프로젝트 세팅의 문제는 아닌 듯 합니다.
Zepeto/Set Scene Lighting 메뉴 역시 적용해보았습니다.

만약 이슈라면 확인해주시면 감사하겠습니다.

이슈가 아닌 정책상의 변경이 있었다면
월드 개발자들이 Quality 설정을 사용할 수 없다면 가이드에 명시해주셨으면 좋겠고
변경에 대해 공지를 해주셨으면 도움이 될 것 같습니다.
```

**개발 환경을 알려주세요.**
`Window 11` `Android 12 (갤럭시 폴드2)`

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.**
![image](https://user-images.githubusercontent.com/100827088/168240471-df2caf0f-1240-4436-a33f-ddfd3a545d2b.png)
```
PC 에디터 상에서 정상적으로 그림자가 렌더링되는 모습
```

![image](https://user-images.githubusercontent.com/100827088/168241323-e2cf5365-379d-444e-a49c-05e8c7eba6c9.png)
```
모바일상에서 Quality 세팅이 변경되어 렌더링되는 모습
```

![image](https://user-images.githubusercontent.com/100827088/168245949-3125a2b4-5e6a-4076-a177-4e37092d81da.png)
```
Quality Preset 세팅은 이미지처럼 한가지만 기본으로 설정하고 사용중입니다.
```

**Comment by Zepeto-TechEvangelist** [comment]
기본적으로 월드의 퀄리티는 제페토 앱의 퀄리티 설정을 따르도록 되어 있습니다.
월드 개별적으로 퀄리티를 다르게 하는 추가 기능 개발 이슈이며 명시한 마일스톤 목표로 진행 중입니다.
감사합니다.
