### ISSUE TITLE
[BUG] : Light >>FogLight>> RenderSettings error

### ISSUE THREAD

**Issue by yoonjoohwan** [naverz/zepeto-studio-kor#766]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
 1.1.5

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
Ex) 3.12.1

**What features were you trying to implement?**
Ex) I want to apply foglight and ambient light to the light.

**What problem did you encounter?**
In C#, you can implement it like this: RenderSettings.fog = (Color)
When I use RenderSettings I get an error

**Please tell us your development environment.**
Window 10 pro
Samsung S9+

**Please attach the implemented code. If you have a screenshot, please attach it.**
        // RenderSettings.ambientLight = this.ambientColor.Evaluate(timePercent);
        // RenderSettings.fogColor = this.FogColor.Evaluate(timePercent);
![image](https://user-images.githubusercontent.com/91707090/168704505-ada52d0f-d053-474a-be22-94a2589b3b11.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요 현재는 지원 불가하여 ForbiddenException 이 발생하는 것입니다.
지원 가능한 방향으로 내부에서 검토해 보겠습니다. 
추후 문의 사항이 있을 경우 디스코드를 사용해 주세요. 
감사합니다.
