### ISSUE TITLE
패키지 업데이트후 ZepetoWorldMultiplay 미노출 이슈

### ISSUE THREAD

**Issue by kihye** [naverz/zepeto-studio-kor#768]
### Discussed in https://github.com/naverz/zepeto-studio-kor/discussions/767

<div type='discussions-op-text'>

<sup>Originally posted by **kihye** May 17, 2022</sup>
![image](https://user-images.githubusercontent.com/80503690/168714333-873fb06f-49ae-450a-94a0-25c2c5f4a717.png)

환경은 윈도우 10입니다.
하위버전에서 업데이트 후에 발생하는 문제같습니다.

1.1.4, 1.1.6 두 버전에서 업데이트 했는데 동일한 문제가 발생합니다.

이것저것 만져봐도 멀티플레이 코드가 나오질 않네요.
스크린샷 예제 프로젝트와 비교해가면서 차이점 찾아보는 중인데 뭔가 특별한 차이라던가 그런건 안보입니다.</div>

**Comment by AcrylicShrimp** [comment]
동일증상 있습니다 `Reimport All`을 해도 해결이 안 됩니다
유일한 해결책은 프로젝트 새로 파서 에셋 다 옮기는것 뿐인 듯 합니다

**Comment by Zepeto-TechEvangelist** [comment]
world package 버전 업 시 간혈적으로 ZepetoWorldMultiplay 컴포넌트가 나타나지 않은 이슈 수정 되었습니다.
1.5.0 적용 예정입니다. 감사합니다.
