### ISSUE TITLE
[BUG] : When you leave the home screen in the mobile environment, the screen changes to portrait mode.

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#769]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.3.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.12.1`

**What features were you trying to implement?**
```
-
```

**What problem did you encounter?**
```
After accessing the world on mobile, press the Android home button to exit the home screen and activate the ZEPETO app again.
The screen in landscape mode changes to portrait.
```

**Please tell us your development environment.**
`Window 11` `Android 12 (Galaxy Fold 2)`

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Cha-SeongHun** [comment]
1.6.0버전에서 동일하게 발생 중입니다

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 다음 버전에서 수정될 예정입니다. 감사합니다.
