### ISSUE TITLE
Prefab에 붙은 ZepetoScript컴포넌트의 변수값이 수정되지 않습니다.

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#771]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)**
`1.3.0`

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)**
`3.12.1`

**어떤 기능을 구현하려고 했나요?**
```
프리팹에 붙은 ZepetoScript 컴포넌트의 변수값을 지정하고 싶어요.
```

**어떤 문제가 발생 하였나요?**
```
씬에 배치된 프리팹의 스크립트에서 아래와 같이 TimeOffset 을 0.5로 변경합니다.
프리팹 내에서 TimeOffset은 0으로 설정되어 있습니다.
```
![image](https://user-images.githubusercontent.com/100827088/168960783-fb76f4ea-b353-4d92-9213-4f4fc083f5cd.png)

```
이후 Play를 누르면 TimeOffset이 프리팹 기본값을 따라 0으로 자동 변경되는 모습을 볼 수 있습니다.
```
![image](https://user-images.githubusercontent.com/100827088/168960799-864785ee-f0ce-4b7a-87f7-9fa4dfd19128.png)
```
원래 유니티 C#스크립트에서는 에디터에 노출된 변수 수정 후 Play를 눌러도 정상적으로 플레이 가능합니다.
제페토 프로젝트에서는 이 증상으로 인해 스크립트의 변수를 에디터에서 조작하는 것이 의미가 없는 상황입니다.

제페토 패키지 버전은 1.3.0이며, 1.1.5 때부터 쭉 존재해 온 이슈입니다.
월드 제작에 있어 크리티컬한 이슈라고 생각됩니다

Discussions에도 업로드한 적 있는 이슈이지만 Issues에 올리는 것이 트래킹이 될 것 같아 추가로 업로드하였습니다.
```

**개발 환경을 알려주세요.**
`Window 11` `Android 12`

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.**

**Comment by Zepeto-TechEvangelist** [comment]
해당 기능은 월드 1.5.0에 추가 될 예정입니다. 감사합니다.
