### ISSUE TITLE
스크립트 재게오류

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-studio-kor#773]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.1.3

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
3.12.0

**어떤 기능을 구현하려고 했나요?
오브젝트 On Off 기능

**어떤 문제가 발생 하였나요?
스크립트가 깨어나지 않아요.

**개발 환경을 알려주세요.
Mac mini (M1, 2020) macOS Monterey 12.3.1

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

오브젝트.SetActive(false) 로 잠시 꺼두고 다시,  오브젝트.SetActive(true) 로 켰을때 제페토 스크립트가 자동으로 작동되지 않음.
해결방법으로 스크립트에 OnEnable 안에 console.log("Awake!")를 적어놓으면 작동함

모든 경우에서 발생하는 버그는 아님

작동안하는 코드
<img width="681" alt="작동안함" src="https://user-images.githubusercontent.com/90679926/169193537-87fb2b72-811b-4d37-a2b1-c0f558245803.png">

작동하는 코드
<img width="681" alt="작동함" src="https://user-images.githubusercontent.com/90679926/169193527-14b2a8b3-360d-480b-a1a7-bd3ba6b70e9b.png">

<img width="902" alt="표" src="https://user-images.githubusercontent.com/90679926/169193284-3e05b02d-f742-40dc-b286-e7959a0bcdc5.png">

에디터에서는 씬 뷰에서 오브젝트를 선택하는것으로도 재게 가능

**Comment by AngeryOrang** [comment]
에디터 상호작용을 통해 관측하면 Update가 도는 슈뢰딩거의 스크립트군요

**Comment by x4cf** [comment]
슈뢰딩거의 스크립트라니 ㅋㅋㅋㅋ XD

**Comment by Shanig123** [comment]
저번에는 Start 전에 update실행되더니 ㄹㅈㄷ ㅋㅋㅋㅋㅋㅋㅋ

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 해당 이슈 원인을 파악하여 다음 마일스톤에 개선 될 예정입니다.
감사합니다.
