### ISSUE TITLE
[BUG] : All scripts do not compile when using a Korean username

### ISSUE THREAD

**Issue by AngeryOrang** [naverz/zepeto-studio-kor#788]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.3.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.12.1

**What features were you trying to implement?**
Haven't tried anything yet.

**What problem did you encounter?**
All Typescripts don't seem to compile if you use a Korean username.
When I select the script file, the inspector shows that NodeJS is not installed.

**Please tell us your development environment.**
Window 10

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 크리에이터님 불편 드려 죄송합니다.
내부에서 확인해 보았으나 이 부분은 수정이 불가한 이슈로 판단되었습니다.  
가급적 영문 사용자 명을 사용하시기를 추천드리며 이 부분을 가이드에도 명시하도록 하겠습니다.
감사합니다.
