### ISSUE TITLE
에디터에서 저장할때마다 오류로그가 발생합니다.

### ISSUE THREAD

**Issue by AngeryOrang** [naverz/zepeto-studio-kor#789]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.3.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
3.12.1

**어떤 기능을 구현하려고 했나요?
프로젝트 저장을 했습니다

**어떤 문제가 발생 하였나요?
오류메세지가 발생합니다

**개발 환경을 알려주세요.
Window 10

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.
![image](https://user-images.githubusercontent.com/105922194/169928693-4f1869f2-a2e8-410b-9837-68ce4dfe13da.png)

**Comment by Zepeto-TechEvangelist** [comment]
위 에러 메세지는 정상적인 실행에는 영향이 없는 known issue입니다.
참고 부탁 드립니다.
