### ISSUE TITLE
패키지 설치 관련 이슈

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#791]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
예) 1.3.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
예) PC

**어떤 문제가 발생 하였나요?
프로젝트 실행 불가 / 실행 해도 패키지가 정상족으로 Import 되지않음

**개발 환경을 알려주세요.
Window10

![image](https://user-images.githubusercontent.com/25768804/169943094-dec6b7ee-eab6-4091-b219-9f202d8e82ad.png)

혹시 몰라 패키지 인스톨러로 패키지 재설치 진행하려 했으나 에러 (500 internal server error)
![image](https://user-images.githubusercontent.com/25768804/169943765-5f4246ab-da30-4bed-8c4d-916ff69ecb06.png)

**Comment by Zepeto-TechEvangelist** [comment]
https://github.com/naverz/zepeto-studio-kor/discussions/787

위 이슈와 동일하게 네트워크나 방화벽 이슈로 추정됩니다.
사내 보안망이시라면 현재로서는 개발이 힘들 것 같습니다.
다만 로드맵 상에 저희가 서버를 제공하는 쪽으로 구성할 계획이 있어서 추후에는 이용이 가능해질 예정입니다.
적용 시기는 미정인 부분 양해 부탁 드립니다.
감사합니다.

**Comment by xowjd913** [comment]
> #787
> 
> 위 이슈와 동일하게 네트워크나 방화벽 이슈로 추정됩니다. 사내 보안망이시라면 현재로서는 개발이 힘들 것 같습니다. 다만 로드맵 상에 저희가 서버를 제공하는 쪽으로 구성할 계획이 있어서 추후에는 이용이 가능해질 예정입니다. 적용 시기는 미정인 부분 양해 부탁 드립니다. 감사합니다.

네트워크 문제도 없고 방화벽도 싹다 풀어놨는데도 이런 이슈가 생기나요 ?
지금까지 잘하고 있다가 패키지 매니저 화면이 안나와서 패키지 디폴트로 초기화 했더니 생긴 문젠데 ..

**Comment by Zepeto-TechEvangelist** [comment]
패키지 매니져 아래와 같이 나왔었나요? 

<img width="792" alt="스크린샷 2022-05-24 오후 12 53 38" src="https://user-images.githubusercontent.com/100118650/169945468-2b10609d-4e4e-4021-b175-248600af2a15.png">

**Comment by xowjd913** [comment]
네 맞습니다.
해당 화면으로 나와서 캐시 초기화 하고 다시 유니티 켰더니
Resolving Packages 하다말고 
![image](https://user-images.githubusercontent.com/25768804/169945708-d8a0f32f-af6d-4531-ba0f-4c51ed8e1430.png)

이렇게 나오네요 ...

**Comment by Zepeto-TechEvangelist** [comment]
확인 감사합니다.

**Comment by xowjd913** [comment]
확인해봤더니 사내 보안망도 아니고 방화벽도 다 풀어놨습니다.
문제가 있어보이네요 ..

**Comment by xowjd913** [comment]
> 확인 감사합니다.

사내 보안망 X / 방화벽 X 인 상태로 생긴 이슈 입니다.
확인 부탁드립니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 내부에서 확인 결과 일시적인 장애가 있었고 복구 완료하였습니다.
잘 되는지 테스트 부탁 드리며, 문제 해결시 이슈 클로징 하겠습니다~ 제보 감사합니다.

**Comment by xowjd913** [comment]
> 안녕하세요, 내부에서 확인 결과 일시적인 장애가 있었고 복구 완료하였습니다. 제보자님 환경에서도 잘 되는지 테스트 부탁 드리며, 문제 해결시 이슈 클로징 하겠습니다~ 제보 감사합니다.

잘 동작 합니다 빠른 이슈 해결 감사합니다 :)
