### ISSUE TITLE
각종 Property undefined

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#819]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.3.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
3.12.1

**어떤 기능을 구현하려고 했나요?
값 참조

**어떤 문제가 발생 하였나요?
각종 Property가 간헐적으로 undefined로 들어옴

**개발 환경을 알려주세요.
Window 10, Android, iOS

게임오브젝트의 매트릭스에 m00 이 undefined
![image](https://user-images.githubusercontent.com/25768804/170934058-d4a85b1f-61dd-4fa2-97b9-bb1c042119e4.png)

게임오브젝트의 name이 undefined
![image](https://user-images.githubusercontent.com/25768804/170934450-3a07edc6-c8dd-43b3-b581-d48d142efead.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 로그 상으로는 게임오브젝트가 이미 undefined 된 것 처럼 보입니다.
좀 더 자세한 코드 정보를 제공해주시면 이슈 해결에 도움이 될 것 같습니다.
감사합니다.

**Comment by xowjd913** [comment]
> 안녕하세요, 로그 상으로는 게임오브젝트가 이미 undefined 된 것 처럼 보입니다. 좀 더 자세한 코드 정보를 제공해주시면 이슈 해결에 도움이 될 것 같습니다. 감사합니다.

```
private *HookingPlayerAnimator() {

        while (this.playerAnimator == null && this.playerNoseJoint) {
            if (ZepetoPlayers.instance &&
                ZepetoPlayers.instance.LocalPlayer &&
                ZepetoPlayers.instance.LocalPlayer.zepetoPlayer &&
                ZepetoPlayers.instance.LocalPlayer.zepetoPlayer.character &&
                ZepetoPlayers.instance.LocalPlayer.zepetoPlayer.character.gameObject) {
                let createdTargetCharacter = ZepetoPlayers.instance.LocalPlayer.zepetoPlayer.character.gameObject;
                if (createdTargetCharacter) {

                    //Get Animator
                    this.playerAnimator = ZepetoPlayers.instance.LocalPlayer.zepetoPlayer.character.ZepetoAnimator; \

                    let childs = createdTargetCharacter.transform.GetComponentsInChildren<Transform>();
                    if (childs) {
                        for (let i = 0; i < childs.length; i++) {
                            if (childs[i].name == "nose") {
                                this.playerNoseJoint = childs[i].gameObject;
                            }
                        }
                    }
                    console.log("[ZepetoPlayerHooker] - Success hooking AnimationController And joints");
                }
            }
            yield new WaitForSeconds(1);
        }
}
```

코드입니다 
로컬 캐릭터가 이미 undefined 되어있는 경우도 있나요?

**Comment by Zepeto-TechEvangelist** [comment]
전달해주신 코드를 통해 현재 버전에서 GetComponentsInChildren 함수를 이용했을 때 배열의 인자가 undefined로 반환되는 이슈를 발견하였습니다.
1.5.0 버전에서 수정 될 예정입니다.
감사합니다.
