### ISSUE TITLE
[BUG] : Does not re-open after pausing the editor

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#823]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.3.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.12.1`

**What features were you trying to implement?**
```
Pause the editor for debugging.
```

**What problem did you encounter?**
```
Unity Editor does not open again after pause.
```

**Please tell us your development environment.**
`Window 11`

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
월드 1.10.0에서 해결되었습니다. 감사합니다.
