### ISSUE TITLE
System.Exception: Server can't start 으로 유니티로  설치가 안됩니다.

### ISSUE THREAD

**Issue by picturestar** [naverz/zepeto-studio-kor#832]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
initializer 0.0.2.0

**어떤 기능을 구현하려고 했나요?
유니티로 월드를 만들고 싶은데 제페토 패키지가 에러 납니다.

**어떤 문제가 발생 하였나요?
유니티에서 제패토가 제대로 설치 되지 않습니다.

**개발 환경을 알려주세요.
 Window 10

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

System.Exception: Server can't start
  at ZEPETO.Script.Compiler.TypescriptCompilerServer.StartServer () [0x000b5] in <04d29a8f697047c3aca3e77e1cabf273>:0 
  at ZEPETO.Script.TypescriptCompilerServerInitializer.Initialize () [0x00006] in <04d29a8f697047c3aca3e77e1cabf273>:0 
  at ZEPETO.Script.Editor.ZepetoScriptEnvironments.InitializeEnvironments () [0x00062] in <868383e0843440a29867f5de362dd887>:0 
UnityEngine.Debug:LogError (object)
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeEnvironments ()
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeTypescript ()

이런 메시지가 계속 나옵니다. 다른 제패토 패키지도 설치가 안됩니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요~유니티 버전은 2020.3.9이고,  Assets → Import Package → Custom Package를 사용해서 제페토 패키지를 가져오는 단계에서 오류가 발생하신 걸까요?

**Comment by picturestar** [comment]
> 안녕하세요~유니티 버전은 2020.3.9이고, Assets → Import Package → Custom Package를 사용해서 제페토 패키지를 가져오는 단계에서 오류가 발생하신 걸까요?
네 일단 거기서 가지고 오면 저런 메시지들이 나옵니다. 그러면서 제패토 관련 소스들이 일부만 들어옵니다. 설치가 제대로 안된고 같은데 해결 방법이 있을까요?

**Comment by Zepeto-TechEvangelist** [comment]
일반적으로는 유니티 재설치 후 시도하는 방법을 권장 드립니다.
저희쪽에서도 재현 테스트를 진행해볼 예정이오니 제보자님도 다시 한번 시도 부탁 드립니다. 🙏

**Comment by picturestar** [comment]
> 일반적으로는 유니티 재설치 후 시도하는 방법을 권장 드립니다. 저희쪽에서도 재현 테스트를 진행해볼 예정이오니 제보자님도 다시 한번 시도 부탁 드립니다. 🙏

저 벌써 3번째 재설치 해봤는데 똑같습니다.
do you want to enable the backends? Doing so will "restart" the editor and will "disable" the old uniteengine. input apis.
라는 문구가 유니티 시작할때 나옵니다. 이것때문에 버그가 나는것 같은데 꼭 해결되었으면 합다.

**Comment by picturestar** [comment]
> > 일반적으로는 유니티 재설치 후 시도하는 방법을 권장 드립니다. 저희쪽에서도 재현 테스트를 진행해볼 예정이오니 제보자님도 다시 한번 시도 부탁 드립니다. 🙏
> 
> 저 벌써 3번째 재설치 해봤는데 똑같습니다. do you want to enable the backends? Doing so will "restart" the editor and will "disable" the old uniteengine. input apis. 라는 문구가 유니티 시작할때 나옵니다. 이것때문에 버그가 나는것 같은데 꼭 해결되었으면 합다.

### [System Info] ###
 
 TTITLE: Current System Basics: 
 Device Model:System Product Name (System manufacturer)
 device name:그림별메인
 device type:Desktop
 device unique identifier:d5fcb516b4b0ef6f06502e4da7ceb710bcf9a187
 graphics card identifier:7089
 graphics card device name:NVIDIA Quadro P4000
 graphics card manufacturer:NVIDIA
 graphics vendor ID:4318
 graphics card support version:Direct3D 11.0 [level 11.1]
 Save (M):8088
 graphic pixel fill rate (megapixel / second), - 1 unknown fill rate:-1
 grade supports shader hierarchy:50
 supports maximum picture size:16384
 npotSupport：Full
 operating system:Windows 10  (10.0.19044) 64bit
 CPU processing core:12
 CPU type:Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
supportedRenderTargetCount：8
supports3DTextures：True
supportsAccelerometer：False
supportsComputeShaders：True
supportsGyroscope：False
supportsImageEffects：True
supportsInstancing：True
supportsLocationService：False
supportsRenderTextures：True
supportsRenderToCubemap：True
supportsShadows：True
supportsSparseTextures：True
supportsStencil：1
supportsVertexPrograms：True
supportsVibration：False
 Memory size:32695
### [Script Project Info] ###
 World Id: com.ZEPETO.me.zepeto.template.default
World Version: 0.1
Max Clients: 8
Screen Orientation: 0
Main Scene Path: 
Installed Zepeto Package Json: 

### [World Package Info] ###
 {
	"name": "zepeto.world",
	"scope": "zepeto",
	"displayName": "ZEPETO.World",
	"version": "1.3.0",
	"unity": "2020.3",
	"description": "Developer Kit for Zepeto World!",
	"keywords": [
		"zepeto",
		"script",
		"javascript",
		"world",
		"v8"
	],
	"zepetoVersion": "3.11.4",
	"category": "Unity",
	"hideInEditor": false,
	"dependencies": {
		"zepeto.world.shared": "1.2.0",
		"zepeto.script": "1.2.0",
		"zepeto.multiplay": "1.2.0",
		"zepeto.multiplay.script": "1.1.2",
		"zepeto.character": "3.1.11",
		"zepeto.character.controller": "1.2.0",
		"zepeto.script.unityengine.typings": "1.0.3",
		"zepeto.iwp": "1.1.0",
		"zepeto.script.leaderboard": "1.1.2",
		"com.unity.scriptablebuildpipeline": "1.15.2",
		"com.unity.editorcoroutines": "1.0.0",
		"com.unity.postprocessing": "3.1.1",
		"com.unity.recorder": "2.5.7",
		"zepeto.world.common": "1.0.0"
	},
	"author": {
		"name": "ZEPETO",
		"email": "support@zepeto.me",
		"url": "https://zepeto.me/"
	},
	"commitId": "873c9fbc7adf919ac7c0d0bceb912d6d02c4174a"
}
버그 리포트를 찾아서 복사해 드립니다. 참고해 주세요

**Comment by Zepeto-TechEvangelist** [comment]
유니티 팝업 창은 New Input System을 사용하겠냐는 확인 창입니다.
이때는 Yes를 눌러주시면 됩니다. 
<img width="754" alt="KakaoTalk_Photo_2022-06-03-15-30-21" src="https://user-images.githubusercontent.com/100118650/171799646-8b36729c-0c9e-46bc-8356-a9af625ab290.png">

동일한 윈도우10에서 정상적으로 설치가 되는데 제보자님 리포트 바탕으로 확인해 보겠습니다. 
<img width="459" alt="KakaoTalk_Photo_2022-06-03-15-30-26" src="https://user-images.githubusercontent.com/100118650/171799667-1d213e66-6b1f-498c-be31-02e1d65d7f06.png">

**Comment by picturestar** [comment]
> 유니티 팝업 창은 New Input System을 사용하겠냐는 확인 창입니다. 이때는 Yes를 눌러주시면 됩니다. <img alt="KakaoTalk_Photo_2022-06-03-15-30-21" width="754" src="https://user-images.githubusercontent.com/100118650/171799646-8b36729c-0c9e-46bc-8356-a9af625ab290.png">
> 
> 동일한 윈도우10에서 정상적으로 설치가 되는데 제보자님 리포트 바탕으로 확인해 보겠습니다. <img alt="KakaoTalk_Photo_2022-06-03-15-30-26" width="459" src="https://user-images.githubusercontent.com/100118650/171799667-1d213e66-6b1f-498c-be31-02e1d65d7f06.png">

제가 2017년 정도에 유니티를 설치하고 이것저것 하던게 남아 있어서 설치가 제대로 안되었습니다. 과거 기록이나 유니티 관련 파일등을 정리하고 다시 설치하니 되었습니다. 번거롭게 해드려서 죄송합니다.

**Comment by picturestar** [comment]
> 유니티 팝업 창은 New Input System을 사용하겠냐는 확인 창입니다. 이때는 Yes를 눌러주시면 됩니다. <img alt="KakaoTalk_Photo_2022-06-03-15-30-21" width="754" src="https://user-images.githubusercontent.com/100118650/171799646-8b36729c-0c9e-46bc-8356-a9af625ab290.png">
> 
> 동일한 윈도우10에서 정상적으로 설치가 되는데 제보자님 리포트 바탕으로 확인해 보겠습니다. <img alt="KakaoTalk_Photo_2022-06-03-15-30-26" width="459" src="https://user-images.githubusercontent.com/100118650/171799667-1d213e66-6b1f-498c-be31-02e1d65d7f06.png">

제가 컴을 포멧까지 해서 다시 설치 했는데 처음에는 이런 오류 없이 잘되다가 빌드 에셋등을 받고 있는데 다시 오류가 났습니다. 지금도 아직 그상태 입니다. 서버가 뭔가 연결이 안되는 것 같은데 꼭 버그 고쳐주시기 바랍니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요 유니티 설치에 대한 이슈는 우선 클로즈 하겠습니다.
빌드 에셋을 받은 이후 발생한 문제에 대해서는 어떤 빌드 어셋인지 알려주시면 파악에 도움이 될 것 같습니다.
감사합니다.
