### ISSUE TITLE
ZEPETO Script Compiler 오류

### ISSUE THREAD

**Issue by devartmaker** [naverz/zepeto-studio-kor#839]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.4.0

**어떤 문제가 발생 하였나요?
기본 템플릿 프로젝트를 열면 아래와 같은 오류가 발생합니다.
오른쪽 하단 TS 컴파일러 아이콘이 어둡게 표현되는걸로 봐서 ZEPETO Script Compiler가 정상적으로 실행되지 못한것 같습니다.
그래서 모든 스크립트가 컴파일이 되지 않습니다.

**개발 환경을 알려주세요.
Window 11

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.
![스크린샷 2022-06-04 오후 9 15 46](https://user-images.githubusercontent.com/40697700/172034337-a783e8e7-a528-4e23-aab0-12df227c1783.png)

[오류 메시지]
System.Exception: Server can't start
  at ZEPETO.Script.Compiler.TypescriptCompilerServer.StartServer () [0x000b5] in <7ed1339551664df39f20f6d7bd945b36>:0 
  at ZEPETO.Script.TypescriptCompilerServerInitializer.Initialize () [0x00006] in <7ed1339551664df39f20f6d7bd945b36>:0 
  at ZEPETO.Script.Editor.ZepetoScriptEnvironments.InitializeEnvironments () [0x00062] in <6d61ff5f97ee4c9b9b82ca163aa79ba7>:0 
UnityEngine.Debug:LogError (object)
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeEnvironments ()
ZEPETO.Script.Editor.ZepetoScriptEnvironments:InitializeTypescript ()

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 혹시 새로운 제페토 템플릿으로 프로젝트를 생성해도 동일한 오류가 발생하는지 확인 부탁 드립니다.

**Comment by devartmaker** [comment]
@Zepeto-TechEvangelist 새로운 템플릿으로 테스트해도 똑같고,
유니티 삭제 & 재설치는 여러 번 했으며,
혹시 윈도우 문제인가 싶어서 노트북 초기화를 해도 똑같은 문제가 발생합니다.

**Comment by Zepeto-TechEvangelist** [comment]
확인 감사드립니다 ㅠ_ㅠ

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 
컴파일 오류를 해결하는 ZEPETO.Script 1.3.4 프리뷰 패키지를 업데이트 하였습니다.
아래의 방법으로 적용 가능합니다.

Window → Package Manager 버튼을 눌러서 Package Manager를 오픈 → [ZEPETO.Script]를 누르고 오른쪽 하단의 Update 버튼을 누릅니다.
1.3.4 preview 버전 업 후 컴파일러 재실행을 위해 유니티를 재시작 해 주세요.
<img width="797" alt="174784909-cdeea83d-0881-4f56-a6cf-7a58a9a4415c" src="https://user-images.githubusercontent.com/100118650/176088925-1462f603-aa9f-4c5e-9b09-37c2b5b0b70c.png">



감사합니다.
