### ISSUE TITLE
1.4.0 업데이트 이후 유니티 인스펙터의 texture,material,shader등의 값이 변경되지 않습니다. 또는 값 초기화가 되지 않습니다.

### ISSUE THREAD

**Issue by YSHFM** [naverz/zepeto-studio-kor#849]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
예) 1.4.0

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
- 유니티 내 문제입니다.

**어떤 기능을 구현하려고 했나요?
- array로 선언된 클래스 멤버 변수를 인스펙터상에서 수정되지가 않습니다.

**어떤 문제가 발생 하였나요?
- array로 선언된 클래스 멤버 변수를 인스펙터상에서 수정되지가 않습니다.

**개발 환경을 알려주세요.
예) Window 10, Unity, PlasticSCM

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

![image](https://user-images.githubusercontent.com/106574541/172335145-5d1a3c99-4c99-4fd8-a92a-17d4dbd6c47b.png)

구현된 코드는 이렇습니다.

하지만 해당 클래스를 오브젝트에 삽입 후 인스펙터를 보면
![image](https://user-images.githubusercontent.com/106574541/172335302-4089bd0b-4ed3-42af-ae33-7353216d78fc.png)
드래그앤 드롭으로 추가할 수가 없습니다.

![image](https://user-images.githubusercontent.com/106574541/172335789-968bde66-7fd5-4532-a119-bf4aaf23b8f4.png)

또한, 이전버전에서 추가된 엘레멘탈이 있는 상태에서 +를 할 경우 해당상태에서 -를 눌러 삭제가 불가능합니다. 위 사진의 경우에선
m_ShaderList의 element2를 삭제할 수가 없습니다. 드래그 드롭으로 변경 또한 불가능합니다.

![image](https://user-images.githubusercontent.com/106574541/172336653-0a8ed253-05c7-4806-9e15-4b4edd7b9b88.png)
또한, 해당 코드에서 new로 인스턴스 헀음에도 스크립트 내 함수에서 해당 컨테이너가 null로 동작됩니다.
![image](https://user-images.githubusercontent.com/106574541/172336856-5f4af4ff-1bdc-4406-b371-25df0636316c.png)
ㄴ Awake나 Start에서 인스턴스 해야만 null로 동작되지 않습니다. 

인스펙터 상에서 array 또는 map 값 조정이 예상과는 다르게 동작되어 빠른 해결이 되었으면 합니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 제보해주신 내용 수정하였고 핫픽스로 다음 업데이트때 반영될 예정입니다.
감사합니다.
