### ISSUE TITLE
[BUG] : World 1.4.0, an issue where Rect Transform is not included in the inspector window

### ISSUE THREAD

**Issue by iamarohan** [naverz/zepeto-studio-kor#859]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.0

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.0

**What features were you trying to implement?**
Ability to drag Rect Transform into Inspector window ZepetoScript

**What problem did you encounter?**
won't be pulled in

**Please tell us your development environment.**
Windows 10

**Please attach the implemented code. If you have a screenshot, please attach it.**
![image](https://user-images.githubusercontent.com/43956286/172765665-8b03d6fb-2389-4f39-b4b6-03c1c115bf1f.png)

**Comment by crash-k** [comment]
It seems to be the same issue as #979.
