### ISSUE TITLE
에러코드 4213이 정확히 어떤 오류인지 알 수 있을까요?

### ISSUE THREAD

**Issue by mahoworld** [naverz/zepeto-studio-kor#866]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.4.1

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
3.13.5

**어떤 문제가 발생 하였나요?
월드 파일 빌드 후 모바일로 테스트를 할 때, 4213이라는 에러 코드와 함께 접속이 되지 않습니다.

**개발 환경을 알려주세요.
Window 11

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

![KakaoTalk_20220608_174917227](https://user-images.githubusercontent.com/99196567/173011110-26572c9c-c86c-4f08-8e80-300d53dfaff1.jpg)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 4213 에러의 경우 멀티플레이 접속후 사용자의 schema 데이터를 받아야 하는데 해당 스키마가 없어서 생긴 이슈 입니다.
내부 확인결과 멀티플레이를 사용하지 않는 프로젝트 인것같은데 
멀티플레이 컴포넌트를 넣어둔 상태라 문제가 되고 있습니다. 
멀티플레이 관련 컴포넌트를 제거한 후 다시 테스트해 보시기를 추천 드립니다.

**Comment by mahoworld** [comment]
아무리 살펴봐도 해당 프로젝트는 멀티 플레이가 정상적으로 작동하고 있는데...
퍼블리시 후 업로드 한 것을 제외한 나머지 환경(QR코드 테스트 등)에서는 아무런 문제 없이 멀티 플레이가 가능합니다...ㅠㅠ
말씀하시는 schema가 어떤 것을 말씀하시는지는 모르겠으나, 유니티 멀티플레이 서버 폴더 내의 schema 정의를 말씀하신 것이라면 어떤 문제가 있는건지..저는 문제를 찾지 못했습니다.
이미 타 프로젝트에서 활용하던 파일을 그대로 가져온 상태인데 다른 월드는 심사 후 문제없이 출시까지 완료되었는데...
프로젝트가 멀티 플레이 기능을 활용하고 있는 상태임을 꼭 알아주시고, 다시 한 번 확인해주세요.

혹시나 확인을 위해 필요한 부분이 있으시다면 말씀해주세요.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요 제출해주신 studio24월드 프로젝트 파일을 확인하였을 때 World.multiplay 내에 아래와 같이 schemas 파일이 있어야 하는데 존재하지 않았습니다.
제출해주신 월드와 테스트 월드가 다르다면 저희쪽에 파일을 공유해주시기를 부탁 드립니다.
감사합니다.

![스크린샷 2022-06-13 오후 4 21 12](https://user-images.githubusercontent.com/100118650/173300664-61c30ad4-f397-4608-9a7f-f50f9dd7cacb.png)

**Comment by mahoworld** [comment]
대용량 첨부파일 1개(75MB)대용량 첨부 파일은 30일간 보관 / 100회까지 다운로드 가능




ZepetoWorldKitTemplate.zip 75MB


  다운로드 기간: 2022/06/14 ~ 2022/07/14






안녕하세요, 파일 공유가 필요하시다고 하셔서 보내드립니다.
흠 ㅠㅠ 제가 확인해본 결과로는 schemas가 잘 있는데 왜 그럴까요...
그래도 혹시 모르니 한번 파일을 보시고 확인해주세요.
 
감사합니다.
 
마호 드림
-----Original Message-----

**Comment by mahoworld** [comment]
[https://drive.google.com/drive/folders/1zBS4yquoovhIGIRtV7sWH99cN2EbeRfg?usp=sharing](url)

**Comment by mahoworld** [comment]
안녕하세요, 파일 용량이 커서 여기에 첨부가 안되는데, 받아보실 수 있는 이메일을 알려주시면 감사하겠습니다.
바로 파일을 보내드릴게요!

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, yura.hwang@naverz-corp.com 으로 보내주시면 됩니다.
감사합니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 전달 드린 메일 확인 부탁 드립니다.
