### ISSUE TITLE
서버 코드에 생략 가능한 중괄호를 생략할 경우 업로드 3단계에서 에러 발생

### ISSUE THREAD

**Issue by hyunjoon-park-metaspace** [naverz/zepeto-studio-kor#876]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.4.1

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
관련 없음

**어떤 기능을 구현하려고 했나요?
빌드 후 업로드를 하려고 했습니다.

**어떤 문제가 발생 하였나요?
서버 코드에 생략 가능한 중괄호를 생략할 경우, 업로드 3단계에서 에러가 발생합니다. 이전 버전에서 이 문제가 해결되었다고 공지되었지만 실제로는 해결되지 않은 것 같습니다.

**개발 환경을 알려주세요.
관련 없음

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.
관련 없음

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 
정확한 문제 해결을 위해 이슈 리포트 양식을 지켜주시기를 부탁 드립니다.
