### ISSUE TITLE
서버 코드에 생략 가능한 중괄호를 생략할 경우 업로드 3단계에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by hyunjoon-park-metaspace** [naverz/zepeto-studio-kor#886]
**제페토 월드 패키지 버전을 알려주세요. (Unity > Window > Package Manager 에서 버전 확인이 가능합니다.)
1.4.1

**현재 설치되어 있는 제페토 앱 버전을 알려주세요. (제페토앱 > MY > 설정 > 버전 에서 버전 확인이 가능합니다.)
관련이 없습니다.

**어떤 기능을 구현하려고 했나요?
프로젝트를 빌드 후 업로드를 하려고 했습니다.

**어떤 문제가 발생 하였나요?
서버 코드에 생략 가능한 중괄호를 생략할 경우, 업로드 3단계에서 에러가 발생합니다. 이전 버전에서 이 문제가 해결되었다고 공지되었지만 실제로는 해결되지 않은 것 같습니다.

**개발 환경을 알려주세요.
Window 11

**구현하신 코드를 첨부해 주세요. 스크린샷이 있다면 첨부해 주세요.

아래와 같이 코드를 수정하니 정상적으로 업로드가 되었습니다. 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/100826500/173538227-81dc03b6-8290-44e2-b7a5-a578be0546be.png)
![image](https://user-images.githubusercontent.com/100826500/173538267-3f22858a-b605-4c94-93e1-7613e332d116.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 내부애서 확인 중입니다.

**Comment by Zepeto-TechEvangelist** [comment]
올려주신 모든 케이스를 서버 코드에 추가해서 테스트해보았으나 저희 쪽에서는 정상적으로 출시가 되었습니다.
원인 파악을 위해 아래 이메일로 서버코드 풀 소스를 전달해 주실 수 있으실까요?
[dl_zepeto_evangelist@naverz-corp.com](mailto:dl_zepeto_evangelist@naverz-corp.com) 입니다.
감사합니다.

**Comment by hyunjoon-park-metaspace** [comment]
안녕하세요, 답장이 늦어 죄송합니다.

조금 더 테스트해본 뒤에 여전히 발생하면 자세한 재현 방법과 함께 이슈 올리겠습니다.

감사합니다.
