### ISSUE TITLE
[BUG] : Materials in SkinnedMeshRenderer become undefined

### ISSUE THREAD

**Issue by ryusiin** [naverz/zepeto-studio-kor#891]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.5

**What features were you trying to implement?**
I tried to apply a translucent shader to the character.

**What problem did you encounter?**
In the case of a SkinnedMeshRenderer, materials (single) can get information, but materials (plural) cannot.
If you turn materials to for, undefined will appear, and if you use forEach, an error will appear.

**Please tell us your development environment.**
Window10

**Please attach the implemented code. If you have a screenshot, please attach it.**

![20220616_132654](https://user-images.githubusercontent.com/5895396/173992657-fdd89b95-bc79-4131-8967-6a7c086d08c7.png)
![20220616_132749](https://user-images.githubusercontent.com/5895396/173992660-7195d4ad-6b89-4bdc-b1f3-e34bfd09d3c8.png)

**Comment by crash-k** [comment]
This was done in zepeto.world@1.6.0
