### ISSUE TITLE
[BUG] : Element in GetPixels of Texture2D is undefined.

### ISSUE THREAD

**Issue by YSHFM** [naverz/zepeto-studio-kor#900]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
- 1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
- 

**What features were you trying to implement?**
- Texture noise masking

**What problem did you encounter?**
-  Texture2D의 GetPixels가 undefined임.

**Please tell us your development environment.**
-  Window 10, unity  2020.3.9, PlasticSCM

**Please attach the implemented code. If you have a screenshot, please attach it.**

I'm writing code to mask an image I put in the inspector with perlin noise.

![image](https://user-images.githubusercontent.com/106574541/174526025-63d26277-104e-4105-86ce-0d13fea8f7fa.png)

This is a code example.

![image](https://user-images.githubusercontent.com/106574541/174526243-6aefd133-b130-4f57-a484-e5efad6f8e9c.png)

This is the execution result.

As you can see it says pix[].r cannot read r from undefind.
As you can see the argument to the console.warn function, pix[y* noiseTex.width + x] is undefined, but _texture.GetPixel(x,y) works.

**Comment by crash-k** [comment]
This was done in zepeto.world@1.6.0
