### ISSUE TITLE
[BUG] : Chat window selected at world start.

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#905]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.5

**What problem did you encounter?**
The button to open the chat window at the start of the world is pressed.

**Please tell us your development environment.**
Android / iOS

**Comment by HenryAtBraveTurtles** [comment]
이거 제페토앱 3.13 인가 업데이트되면서 이렇게 바뀐 것 같던데.. 많이 불편하더라고요 채팅창 영역 뒤에 다른 UI 터치를 막아버려서..ㅠㅠ

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 채팅 창이 기본적으로 열려있도록 변경되면서 불편한 월드들이 다수 존재하는 것을 인지하였습니다.
채팅창이 기본적으로는 off가 되도록 변경할 예정이고 
궁극적으로는 크리에이터 월드에서 채팅 UI를 on/off하는 API를 제공하는 방안도 고려 중에 있습니다.
적용 시기는 추후에 작업 완료 시점에 공유 드릴 예정입니다. 
감사합니다.

**Comment by HenryAtBraveTurtles** [comment]
의견 반영해주셔서 감사합니다!

**Comment by crash-k** [comment]
Applied to ZEPETO 3.16.0.
