### ISSUE TITLE
[BUG] : When taking a QR code, the screen is cut in half

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#910]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.5

**What problem did you encounter?**
QR코드 좔영시 QR 코드 촬영화면 반 로딩화면 반 잘려서 보이는 경우가 간헐적으로 있음.

**Please tell us your development environment.**
Android / iOS

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 저희 쪽에서 재현되지 않는 이슈입니다.
최신 월드에서도 발생하는지 확인 부탁드리며 발생시 디스코드를 통해 제보 부탁 드립니다.
감사합니다.
