### ISSUE TITLE
[BUG] : ZEPETO scripts refactored in the IDE do not compile

### ISSUE THREAD

**Issue by AngeryOrang** [naverz/zepeto-studio-kor#911]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.5

**What features were you trying to implement?**

**What problem did you encounter?**
ZEPETO scripts refactored in IDEs such as VSCode cannot be built.
Even if it does not play or plays, only the code before modification continues to be executed, or the corresponding module is constantly missing.

I think this problem occurs because the modified codes are not compiled.

If you modify each code file one by one, it compiles again, but please provide a means to forcibly clear the compilation cache.

**Please tell us your development environment.**
Window 10

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 컴파일 캐시 삭제는 아래 방법을 시도해 보세요.

1. ZEPETO - Script - All Rebuild
2. 불러오지 못하는 TS 파일을 선택하여 inspector 에서 force rebuild

안내드린 방법으로도 계속 문제가 발생한다면 댓글로 알려주세요.
감사합니다.

**Comment by Cha-SeongHun** [comment]
https://github.com/naverz/zepeto-studio-kor/issues/833 
위 링크와 동일이슈로 보입니다

**Comment by Zepeto-TechEvangelist** [comment]
월드 1.6.0에서 해결된 이슈로 클로징 처리하겠습니다. 감사합니다.
