### ISSUE TITLE
[BUG] : World freezes while playing on mobile

### ISSUE THREAD

**Issue by AngeryOrang** [naverz/zepeto-studio-kor#932]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.6

**What features were you trying to implement?**
I tried to test the world I made

**What problem did you encounter?**
While testing on my phone, the world suddenly freezes.
All occurrences have been confirmed in the production world and official samples.
It seems like a bug if you see that the script was not used and the system UI stopped together.
Both Android and iPhone models have stopped working.

**Please tell us your development environment.**
Window 10, IOS 15

**Please attach the implemented code. If you have a screenshot, please attach it.**

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 제페토 앱에 올라간 다른 월드 플레이에서도 동일한 현상이 나타나나요?
만약 제작하신 월드에서만 발생하는 이슈라면
패키지 파일을 등록하신 후 월드 id를 알려주시면 보다 정확한 원인 파악이 가능 할 것 같습니다.

**Comment by Zepeto-TechEvangelist** [comment]
확인 결과 ZepetoPlayers 의UIController_Vertical(Horizontal) 프리팹이 제거되어 발생한 현상으로 보여집니다.
프리팹 설정시 정상 동작 할 것입니다.
공식 샘플에서도 최신 버전으로 업데이트하면서 반영해둘 예정입니다.
감사합니다.
