### ISSUE TITLE
[BUG]: HasPlayer(), OnAddedLocalPlayer() 함수를 찾지 못함

### ISSUE THREAD

**Issue by smlee2952** [naverz/zepeto-studio-kor#958]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
1.4.1

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
3.13.6

**What features were you trying to implement?**
(https://www.youtube.com/watch?v=H92Gd2G9DhM) 예제를 보고 따라서 진행

**What problem did you encounter?**
유튜브와 코드도 같고, 빌드도 잘되고 문제가 없어 보이는데 실행만 하면 에러를 출력함
![image](https://user-images.githubusercontent.com/49216499/177158557-784d13e7-f191-411f-bdc9-1a5d7c29092f.png)

**Please tell us your development environment.**
Window 10

**Please attach the implemented code. If you have a screenshot, please attach it.**
코드는 아래와 같습니다.

vscode 상 32번째 줄 HasPlayer() 를 찾을 수 없다고 Unity에서 에러를 출력합니다.
또한 가끔 vscode 상 46번째 줄 OnAddedLocalPlayer() 또한 찾을 수 없다고 에러를 출력합니다.

감사합니다.

![image](https://user-images.githubusercontent.com/49216499/177158694-524ffebb-315d-4b75-8a8a-f36d265be35a.png)

**Comment by smlee2952** [comment]
확인 결과 ZepetoPlayers.instance 자체가 null 이라서 발생하는 문제인데 이유는 아직 모르겠습니다.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, ZepetoPlayers가 씬 내에 추가되어 있고 멀티플레이 서버를 켜고 Play를 했는데도 ZepetoPlayers.instance가 null이 뜬 상황일까요?

**Comment by smlee2952** [comment]
확인 결과 ZepetoPlayers가 씬 내에 추가 되어 있지 않았습니다.

https://studio.zepeto.me/guides/multiplay-tutorial
위 링크 튜토리얼을 보면서 진행 중이였는데, 3편 끝날때 까지는 ZepetoPlayers를 추가하는 내용이 없었는데
4편 시작할때는 이미 ZepetoPlayers가 추가 되어 있어 해당 부분을 놓친 것 같습니다.

문제 해결되었습니다.
감사합니다.

**Comment by Zepeto-TechEvangelist** [comment]
다행입니다~! 이슈 클로즈 하겠습니다 :)
