### ISSUE TITLE
playerId ,zepetoId ,userId의 차이점이 뭐죠?

### ISSUE THREAD

**Issue by bestdeveloperjo** [naverz/zepeto-studio-kor#964]
playerId
zepetoId : 제페토 계정 아이디
userId 

이렇게 알고있습니다.

나머지  playerId,userId는 어떤 용도의 아이디 입니까?

_Originally posted by @bestdeveloperjo in https://github.com/naverz/zepeto-studio-kor/discussions/963_

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 답변은 Discussions에 올려주신 질문에서 진행 하겠습니다.
이슈는 close 하겠습니다.
