### ISSUE TITLE
[BUG]: Assets is not assigned to the slot in inspector

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#979]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.4.1`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.13.6`

**What features were you trying to implement?**
```
I want to register Assets in the Inspector.
```

**What problem did you encounter?**
```
Assets is not assigned to the slot in inspector.
```

**Please tell us your development environment.**
`Window 11`

**Please attach the implemented code. If you have a screenshot, please attach it.**
![InspectorInputIssue](https://user-images.githubusercontent.com/100827088/177925313-f376592d-7ea5-4714-bd81-267a2d0f1301.gif)

**Comment by Cha-SeongHun** [comment]
Same problem with version 1.5.1.

**Comment by Cha-SeongHun** [comment]
Same problem with version 1.6.0.

**Comment by Cha-SeongHun** [comment]
Also, if I save world in this state and restart the Unity editor, the modifications are lost.

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 다음 월드 버전에 적용 예정입니다. 감사합니다.
