### ISSUE TITLE
[BUG]: 1.5.0 패키지 업데이트 문제

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-studio-kor#990]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
ex) 1.4.1

1.5.0 패키지 매니저에서 업데이트 시 사용중인 리소스를 변경하는지 에러가 나면서 업데이트가 진행되지않음

![image](https://user-images.githubusercontent.com/25768804/178396592-3c93b4d4-3fb1-458e-9ffa-12fb44d6cbfc.png)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요, 열려있는 에디터 등을 다 닫고 다시 업데이트를 시도해보시겠어요?

**Comment by xowjd913** [comment]
> 

껐다 켜자마자 다른거 안하고 바로 업데이트 하니까 정상적으로 진행되네요 감사합니다 :)
