### ISSUE TITLE
[BUG]: Fails to compile my code on 1.5.0

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#991]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.5.1`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.13.6`

**What features were you trying to implement?**
```
I just upgraded from 1.4.1 to 1.5.0 and played it on the Unity Editor.
```

**What problem did you encounter?**
```
It fails to launch with below error message.

TypeError: Cannot read property 'escapedName' of undefined

My code doesn't have identifier named escapedName, so I think it's not my fault. More over, this project was successfully launched before upgrade.
```

**Please tell us your development environment.**
Window 11

**Please attach the implemented code. If you have a screenshot, please attach it.**
![image](https://user-images.githubusercontent.com/100827088/178406106-690619c1-c469-4eea-8afb-eff36cf31946.png)

**Comment by Cha-SeongHun** [comment]
The compilation error occurs when `for` statement is exists. If you comment out the statement below, the compilation succeed as usual.

```ts
MultiplayClient.AddMessageHandler(PacketTypeS2C.GameResult, (messageObj) => {
            const packet = messageObj.toString();
            const elements = packet.split("//");

            const scorePackets = elements[1].split("/");

            // A problematic code ↓↓↓
            for (const scorePacket of scorePackets) {

            }
            // ↑↑↑
});
```

**Comment by HenryAtBraveTurtles** [comment]
Same problem on my end. Hope it gets fixed soon.

**Comment by Cha-SeongHun** [comment]
As in the syntax below, specifying the Type explicitly will resolve the error.
```ts
const scorePackets: string[] = a.split("/");
 for (const scorePacket of scorePackets) {

 }
```
This seems to be a problem with the compiler.

**Comment by HenryAtBraveTurtles** [comment]
@Cha-SeongHun Thank you for the solution! You saved my life :)
