### ISSUE TITLE
[BUG]: I Can't set Importer setting of ZepetoScript on 1.5.0 package

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#992]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.5.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.13.6`

**What features were you trying to implement?**
```

```

**What problem did you encounter?**
```
Some scripts shared by servers and clients, like `PacketType: Enum`.

So I want set script's importer setting in world.multiplay.
But when I set it, It rollback to the previous state automatically.

```

**Please tell us your development environment.**
`Window 11` `Android 11`

**Please attach the implemented code. If you have a screenshot, please attach it.**
![ChangeImporter](https://user-images.githubusercontent.com/100827088/178411430-b07df3f9-301d-4604-96f1-19ce21111981.gif)

**Comment by jhslee** [comment]
Verified to be an issue as of `1.5.1` when creating a typescript from within the multiplay folder it prevents the asset importer setting, but if the script is moved outside the multiplay folder and changed there its possible, and if returned to the typescript folder, the Asset Importer setting sticks with the script file.
